### ISSUE TITLE
Updates:

### ISSUE THREAD

**Issue by JOHNJACOBJlNGLEHEIMERSCHMIDT** [teakhanirons/RandomHentai#1]
I am not a lua programmer; so I make no guarantees about the below code, except that it functions for me. and probably has bugs. anyways here are the features:
-a file index (as well as an index number in the bottom left corner) allowing you to save the images generated.
-a new file save directory. to keep things organized.

**you have to manually create the directory: ux0:/data/hent/**
To install: overwrite index.lua with this. (feel free to mod this code into a new version. (though it really should create the directory on its own. I just couldnt figure it out)

Controls:
L1 to go back 1 position in the index, R1 to go forward 1 position
X to overwrite the image in the current position with a new randomly generated image
Left to overwrite index -1 with a new random image (because sometimes an image crashes the program)
Right to overwrite index+1

[index.zip](https://github.com/teakhanirons/RandomHentai/files/3032016/index.zip)

**Comment by teakhanirons** [comment]
Discussed via email. Closing the issue.
